owner-name: Koki
swagger-api-license: Koki`s License
swagger-api-term: Only user for persons associated
swagger-api-version: v1
swagger-description: Student Service
swagger-title: Koki Student Service API's



server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:file:~/catalogue;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;SCHEMA=Student
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql : true
        generate_statistics : false
 # spring.datasource.url=jdbc:h2:file:~/catalogue;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  # spring.datasource.driverClassName=org.h2.Driver
  # spring.datasource.username=sa
  #spring.datasource.password=
  # spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  # Enabling H2 Console
  # spring.h2.console.enabled=true
  # Custom H2 Console URL
  # spring.h2.console.path=/h2-console
  # create database schema from SQL files
  # spring.jpa.hibernate.ddl-auto=none
  #Turn Statistics on and log SQL stmts
  # spring.jpa.show-sql=true
  # spring.jpa.properties.hibernate.format_sql=true
  # spring.jpa.properties.hibernate.generate_statistics=false
  h2:
    console:
      enabled: true
      path: /h2-console
#logging.level.org.hibernate.type=trace